theme = "hugo-blog-awesome"
publishDir = "docs"
baseURL = "/"
title = "BK's Blog"
languageCode = "en-us"
author = "Brandon Kurtz"
googleAnalytics = "UA-212195209-1"

[markup.goldmark.renderer]
    unsafe = true

[params]
    description = "I am a Client Platform Engineer. I like to use golang, config management, and open-source management tools. Views are my own."
    avatar = "static/avatar.jpg"
[[menu.main]]
    url = "https://github.com/discentem/"
    name = "Github"
    weight = 2
[[menu.main]]
    url = "https://www.linkedin.com/in/brandon-kurtz/"
    name = "Linkedin"
    weight = 3