theme = "m10c"
publishDir = "docs"
baseURL = "https://bkurtz.io"
title = "BK"
languageCode = "en-us"
author = "Brandon Kurtz"
googleAnalytics = "UA-212195209-1"

[markup.goldmark.renderer]
    unsafe = true

[params]
    description = "I am Client Platform Engineer. I like to use golang, config management, and open-source management tools. Views are my own."
    avatar = "static/avatar.jpg"
[[menu.main]]
    url = "/"
    name = "Blog"
    weight = 1

[[params.social]]
    icon = "github"
    url = "https://github.com/discentem/"
[[params.social]]
    url = "https://macadmins.slack.com/messages/D1PJBJWLT"
    icon = "slack"
[[params.social]]
    url = "https://twitter.com/muffins222221"
    icon = "twitter"
[[params.social]]
    icon = "linkedin"
    url = "https://www.linkedin.com/in/brandon-kurtz/"