name: Push to GitHub Pages on push to main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@main
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          HUGO_VERSION: 0.88.0
          TARGET_REPO: discentem/discentem.github.io
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.token }}
          CNAME: www.bkurtz.io